### PR TITLE
Allow bower install to run in root context

### PR DESCRIPTION
**Pull request by abh1kg**
Bower is a user command but needs to be run in root user context to support automated builds.

### CODE REVIEW

**Comment by hsiliev** [comment]
Why exactly do we need root? Because of tests (phantom) or for other reasons?

**Comment by abh1kg** [comment]
The root context is needed to run the builds on concourse. The build currently fails because it treats the `bower install` command as a user command.

**Comment by hsiliev** [comment]
Correct me if I'm wrong, but this usually means we use dependencies that require root access?
I was interested in the dependencies we have that require such access?

**Comment by abh1kg** [comment]
@hsiliev  Actually we do not use any dependencies that require root access on their own. 
The allow-root option is only needed to install the dependencies using bower, when the user context is "root".

**Comment by hsiliev** [comment]
Ok - got it. In Concourse we are running as root and this makes bower sad.

However I'm concerned having this option permanently in the postinstall. Someone downloading the broker might run it as root and this is never a good idea.

I would prefer to have an env.variable that controls the behaviour of this script, so we can allow root only for Concourse.

**Comment by abh1kg** [comment]
Agreed. But, I would postpone that to replacing bower with "yarn + webpack" for the frontend dependencies. Then, we can solve the problem more gracefully.

**Comment by hsiliev** [comment]
Can you create an issue about replacing bower with yarn & webpack and getting rid of enabled root access then?

**Comment by abh1kg** [comment]
Created https://github.com/cloudfoundry-incubator/cf-abacus-broker/issues/25 to track the move to yarn + webpack

**Pull request merged**
