### PR TITLE
Read default plans and mappings from abacus-provisiong-plugin

### PR DESCRIPTION
**Pull request by georgi-lozev**
Signed-off-by: Vasil Petkov <v.petkov@sap.com>

### CODE REVIEW

**Comment by georgi-lozev** [comment]
Please do not merge, we need to check the shrink-wrap file.

**Comment by hsiliev** [comment]
Do we really want to have the original modules & the extension ones side-by side? The original idea of the Abacus plugins is to replace the dummy implementation with a customized one. 

This change requires the original modules just because we need the plans and mappings if I understood correctly. Wouldn't it be better to split the mappings and plans in a separate modules and require just these resources instead?

**Comment by georgi-lozev** [comment]
Yes, it makes sense to have a separate module where the plans and mappings are extracted and this module is referenced both from the original dummy provisioning and this extension provisioning. However those changes will spread across both cf-abacus and cf-abacus-broker. 

From my point of view the changes in this PR are the second best option instead of having it duplicated in both repositories, like it's right now.

**Comment by georgi-lozev** [comment]
I've added the updated dependencies file.

**Comment by hsiliev** [comment]
I still think having the plans/mappings in separate module would be a better solution. 

We can merge this PR as an intermediate step, provided that we create an issue to track the work on splitting the resources.

**Comment by georgi-lozev** [comment]
Here is the corresponding issue https://github.com/cloudfoundry-incubator/cf-abacus-broker/issues/78

**Pull request merged**
